### ISSUE TITLE
Suggest link page : 404

### ISSUE THREAD

**Issue by tiritibambix** [GeorgeSG/sub.rehab#13]
The suggest link page leads to a 404 - Page Not Found

![Screenshot_2023-06-23-21-58-13-35_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/GeorgeSG/sub.rehab/assets/69852851/af01b7a3-c3e3-4e76-9357-97ef3495dcc8)

**Comment by GeorgeSG** [comment]
Submissions are not open yet. Very soon though :)

**Comment by schackbrian2012** [comment]
"Suggesting links is currently disabled."

https://sub.rehab/submit-link/

**Comment by forenta** [comment]
replacing 404 with 'currently disabled' is a funny way to close an issue.

Is there *any* way left to suggest reddit-replacement-communities?

**Comment by GeorgeSG** [comment]
@forenta suggesting links is currently disabled.

The original issue was referencing a bug that I fixed on June 23rd and that's why I closed it.

**Comment by schackbrian2012** [comment]
@GeorgeSG Thank you for the clarification. As I understand, this issue "Suggest link page : 404" is about the "404 - Page Not Found" error message. This issue is currently resolved. But submitting links is still not currently possible because it is disabled. Is this correct?

**Comment by GeorgeSG** [comment]
@schackbrian2012, yes, that's correct.

Moderating and approving new links takes a decent amount of time, which I can't currently devote to the project.

**Comment by schackbrian2012** [comment]
No worries, I understand!
